export enum ErrorCode {
    NOT_WHITELISTED = 'NOT_WHITELISTED',
    ALREADY_REGISTERED = 'ALREADY_REGISTERED',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    BAD_REQUEST = 'BAD_REQUEST',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    SUCCESS = 'SUCCESS'
}